### ISSUE TITLE
YAML? からスニペットファイルを自動生成する?

### ISSUE THREAD

**Issue by pizzacat83** [pizzacat83/math-gorilla#2]
楽かもしれないしそうでもないかもしれない

```yml
- name:
  - 'lrparens'
  - 'par'
  body: '\left($1\right)'
```

↓

```json
"UNIQUE_ID": {
  "scope": ["markdown"],
  "prefix": ["lrparens", "\\lrparens", "par", "\\par"],
  "body": ["\\left($1\\right)"],
},

```
